use_map_topic: true
# Publish scans from best pose at a max of 10 Hz -->
odom_model_type: diff
odom_alpha5 value: 0.1
gui_publish_rate value: 5.0 #10.0
laser_max_beams value: 60
laser_max_range value: 12.0
min_particles value: 500
max_particles value: 2000
kld_err value: 0.05
kld_z value: 0.99
odom_alpha1 value: 0.2
odom_alpha2 value: 0.2

# Translation std dev, m -->
odom_alpha3 value: 0.2
odom_alpha4 value: 0.2
laser_z_hit value: 0.5
laser_z_short value: 0.05
laser_z_max value: 0.05
laser_z_rand value: 0.5
laser_sigma_hit value: 0.2
laser_lambda_short value: 0.1
laser_model_type value: likelihood_field
laser_likelihood_max_dist value: 2.0
update_min_d value: 0.25
update_min_a value: 0.2
odom_frame_id value: odom
resample_interval value: 1

# Increase tolerance because the computer can get quite busy
transform_tolerance value: 1.0
recovery_alpha_slow value: 0.0
recovery_alpha_fast value: 0.0