footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1]]
footprint_padding: 0.01

global_frame: odom
robot_base_frame: base_footprint #base_link
update_frequency: 2.0 #5.0
publish_frequency: 0.5 #3.0
transform_tolerance: 1.0 #0.5

raytrace_range: 3.5

resolution: 0.05

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, obstacle_range: 2.5}

inflation:
    cost_scaling_factor: 10.0 #0.5
    inflation_radius: 0.2
